### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by nissessenap** [AmiditeX/mimir-operator#4]
Hi @AmiditeX 

First of all, great job!
Really fun to see that someone else wanted a similar way of working like the prometheus operator.

This is my initial thoughts when reading the code. If you want, we can also jump in to a call and discuss more.
But I got a bit lazy to create an issue for each thing.

### Operator or controller?
Are you really going to make an operator? You even write in the README this is a controller.
My understanding of operator vs controller, is that an operator will manage the application. While a controller will "only" configure an API.
I really recommend that we stick to a controller, writing deployment config is a pain and Mimirs helm chart looks okay for me. 

### Group name

You are currently calling the group `mimir.grafana.com`, I personally think it's a bit too generic.
Having your main domain be `grafana.com` isn't ideal for potential future things.
For example, in the grafana-operator we call our group  [grafana.integreatly.org](https://github.com/grafana-operator/grafana-operator/blob/master/api/v1beta1/groupversion_info.go) which i think is an old internal team name at RedHat.
But the good thing is that none else will ever put a claim on it, and it won't potentially crash with someone else's operator/controller.

### rules logic

What is the reason why Rules are optional? https://github.com/AmiditeX/mimir-operator/blob/766396be130d01a65224a1ec9ef36478634065a0/api/v1alpha1/mimirtenant_types.go#L15
Can this controller do anything without a selector? I think you can remove some logic if you make this required.

### mimirtool cli

Currently, you are shelling out to mimirtool, is this a good idea?
I haven't looked at mimirtool code at all, would it be possible to use the APIs instead?

### Alertmanager config

Another feature that we see is to manage AlertmanagerConfig that is also tenant ID specific.
Is this something that you would be willing to have added to this controller as well?
If we decide to do this, it's probably a good idea to have a separate reconciler.

The CRDs could look something like this:

One could be called:
Kind: MimirRules, which is the current reconciler

```yaml
apiVersion: mimir.grafana.com/v1alpha1
kind: MimirRules
metadata:
  name: mimirtenant-sample
  namespace: default
spec:
  id: "tenant1" # ID of the tenant in Mimir (X-ScopeOrg-ID header)
  URL: "http://mimir-ruler.instance.com"
  rule:
    selectors:
      matchLabels:
        helm.sh/chart: loki-4.10.1
```

Kind: MimirAlertManagerConfig
Would be very similar but would have some other endpoints 

```yaml
apiVersion: mimir.grafana.com/v1alpha1
kind: MimirAlertManagerConfig
metadata:
  name: mimirtenant-sample
  namespace: default
spec:
  id: "tenant1"
  URL: "http://mimir-alertmanager.instance.com"
  alertManagerConfig:
    selectors:
      matchLabels:
        helm.sh/chart: loki-4.10.1
```

**Comment by eiTi3Aishieg** [comment]
Hi,

Thanks for the great feedback, I'll address every point below.

# Operator or controller?

The README was partially initialized by the operator-sdk, so any use of the term "controller" is according to their definition (which I'm not sure of, seems like controllers are sub-elements of an operator in their examples).
I also think  we should stay on the "configure Mimir" side of things. Installing Mimir through CRDs doesn't seem to be something that would be of much use; considering it isn't the kind of tool to be repeatedly provisionned unless we're doing Mimir as a Service.

# Group name
I thought the same thing but couldn't come with something better, I'm open to suggestions.

# Technical

Rules are optional because of future possibles uses for the CRD (configuring AlertManager, configuring limits for the tenant), and someone in need of the operator to configure limits might not need to also configure rules. Right now, considering the code only treats the "Rules" section in a reconciliation loop, there's little sense in it being optional, but in the future, it might be needed.

Concerning selectors: if no selector is specified for a rule, all the rules in the cluster are sent to Mimir. I put an example of that in the documentation. This is needed because there's no (AFAIK) selector to "select all".  

# Future

I do plan on having alertmanager/limits in the controller (I have internal needs for that myself). Now, concerning breaking up the configuration in multiple CRDs, I have no strong feelings towards one or the other. Considering they would indeed share some fields (id, url, authentication?), I initially thought about having something like this:

```yaml
apiVersion: mimir.grafana.com/v1alpha1
kind: MimirTenant
metadata:
  name: mimirtenant-sample
  namespace: default
spec:
  id: "tenant1"
  URL: "http://mimir-alertmanager.instance.com"
  alertManagerConfig:
    selectors:
      matchLabels:
        helm.sh/chart: loki-4.10.1
  rule:
    selectors:
      matchLabels:
        helm.sh/chart: loki-4.10.1
```

You probably understand now why I chose to have the rules optional. This format for the CRDs fits my future needs, but I totally get your format aswell.

Again, thanks for the great feedback.
